In [1]:
import pandas as pd

In [2]:
data = "resources/measurement.csv"
data2 = "resources/station.csv"

In [40]:
measurements = pd.read_csv(data)
stations = pd.read_csv(data2)
pd.isnull(measurements)

          id  station   date   prcp   tobs
0      False    False  False  False  False
1      False    False  False  False  False
2      False    False  False  False  False
3      False    False  False  False  False
4      False    False  False   True  False
5      False    False  False  False  False
6      False    False  False  False  False
7      False    False  False  False  False
8      False    False  False  False  False
9      False    False  False  False  False
10     False    False  False  False  False
11     False    False  False  False  False
12     False    False  False  False  False
13     False    False  False  False  False
14     False    False  False  False  False
15     False    False  False  False  False
16     False    False  False  False  False
17     False    False  False  False  False
18     False    False  False  False  False
19     False    False  False  False  False
20     False    False  False  False  False
21     False    False  False  False  False
22     False    False  False  False  False
23     False    False  False  False  False
24     False    False  False  False  False
25     False    False  False  False  False
26     False    False  False   True  False
27     False    False  False  False  False
28     False    False  False  False  False
29     False    False  False   True  False
...      ...      ...    ...    ...    ...
19520  False    False  False  False  False
19521  False    False  False  False  False
19522  False    False  False  False  False
19523  False    False  False  False  False
19524  False    False  False  False  False
19525  False    False  False  False  False
19526  False    False  False  False  False
19527  False    False  False  False  False
19528  False    False  False   True  False
19529  False    False  False  False  False
19530  False    False  False  False  False
19531  False    False  False   True  False
19532  False    False  False   True  False
19533  False    False  False  False  False
19534  False    False  False  False  False
19535  False    False  False  False  False
19536  False    False  False  False  False
19537  False    False  False   True  False
19538  False    False  False  False  False
19539  False    False  False   True  False
19540  False    False  False  False  False
19541  False    False  False  False  False
19542  False    False  False  False  False
19543  False    False  False  False  False
19544  False    False  False   True  False
19545  False    False  False  False  False
19546  False    False  False   True  False
19547  False    False  False  False  False
19548  False    False  False  False  False
19549  False    False  False  False  False

[19550 rows x 5 columns]

In [41]:
pd.isnull(stations)

      id  station   name  latitude  longitude  elevation  location
0  False    False  False     False      False      False     False
1  False    False  False     False      False      False     False
2  False    False  False     False      False      False     False
3  False    False  False     False      False      False     False
4  False    False  False     False      False      False     False
5  False    False  False     False      False      False     False
6  False    False  False     False      False      False     False
7  False    False  False     False      False      False     False
8  False    False  False     False      False      False     False

In [46]:
measurements.fillna(value =0, inplace = True)

In [47]:
measurements.to_csv("clean_measurements.csv")

In [48]:
stations.to_csv("clean_stations.csv")