In [170]:
import pandas as pd
import matplotlib.pyplot as plt
import sqlite3
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine
import numpy as np
from sqlalchemy import func
from sqlalchemy import desc

In [77]:
base = automap_base()
engine = create_engine("sqlite:///hawaii.sqlite")
base.prepare(engine,reflect=True)

conn = sqlite3.connect("hawaii.sqlite")
cur = conn.cursor()
res=cur.execute("SELECT name FROM sqlite_master WHERE type='table'ORDER BY name;")
for name in res:
    print(name[0])

Measurements
Stations

In [78]:
measurement = base.classes.Measurements
station = base.classes.Stations
session=Session(engine)

In [79]:
date_prcp = session.query(measurement.date, measurement.prcp).\
    filter(measurement.date >= "2016-08-23")

In [80]:
df = date_prcp.all()

In [81]:
new_df = pd.DataFrame(df)
new_df.set_index("date", inplace = True)
new_df

            prcp
date
2016-08-23   0.0
2016-08-24  0.08
2016-08-25  0.08
2016-08-26   0.0
2016-08-27   0.0
2016-08-28  0.01
2016-08-29   0.0
2016-08-30   0.0
2016-08-31  0.13
2016-09-01   0.0
2016-09-02   0.0
2016-09-03   0.0
2016-09-04  0.03
2016-09-05   0.0
2016-09-06   0.0
2016-09-07  0.05
2016-09-08   0.0
2016-09-09  0.03
2016-09-10   0.0
2016-09-11  0.05
2016-09-12   0.0
2016-09-13  0.02
2016-09-14  1.32
2016-09-15  0.42
2016-09-16  0.06
2016-09-17  0.05
2016-09-18   0.0
2016-09-19   0.0
2016-09-20   0.0
2016-09-21   0.0
...          ...
2017-07-24  0.84
2017-07-25   0.3
2017-07-26   0.3
2017-07-27   0.0
2017-07-28   0.4
2017-07-29   0.3
2017-07-30   0.3
2017-07-31   0.0
2017-08-01   0.0
2017-08-02  0.25
2017-08-03  0.06
2017-08-05   0.0
2017-08-06   0.0
2017-08-07  0.05
2017-08-08  0.34
2017-08-09  0.15
2017-08-10  0.07
2017-08-11   0.0
2017-08-12  0.14
2017-08-13   0.0
2017-08-14  0.22
2017-08-15  0.42
2017-08-16  0.42
2017-08-17  0.13
2017-08-18   0.0
2017-08-19  0.09
2017-08-20   0.0
2017-08-21  0.56
2017-08-22   0.5
2017-08-23  0.45

[2230 rows x 1 columns]

In [82]:
new_df['prcp'].astype(float)

date
2016-08-23    0.00
2016-08-24    0.08
2016-08-25    0.08
2016-08-26    0.00
2016-08-27    0.00
2016-08-28    0.01
2016-08-29    0.00
2016-08-30    0.00
2016-08-31    0.13
2016-09-01    0.00
2016-09-02    0.00
2016-09-03    0.00
2016-09-04    0.03
2016-09-05    0.00
2016-09-06    0.00
2016-09-07    0.05
2016-09-08    0.00
2016-09-09    0.03
2016-09-10    0.00
2016-09-11    0.05
2016-09-12    0.00
2016-09-13    0.02
2016-09-14    1.32
2016-09-15    0.42
2016-09-16    0.06
2016-09-17    0.05
2016-09-18    0.00
2016-09-19    0.00
2016-09-20    0.00
2016-09-21    0.00
              ...
2017-07-24    0.84
2017-07-25    0.30
2017-07-26    0.30
2017-07-27    0.00
2017-07-28    0.40
2017-07-29    0.30
2017-07-30    0.30
2017-07-31    0.00
2017-08-01    0.00
2017-08-02    0.25
2017-08-03    0.06
2017-08-05    0.00
2017-08-06    0.00
2017-08-07    0.05
2017-08-08    0.34
2017-08-09    0.15
2017-08-10    0.07
2017-08-11    0.00
2017-08-12    0.14
2017-08-13    0.00
2017-08-14    0.22
2017-08-15    0.42
2017-08-16    0.42
2017-08-17    0.13
2017-08-18    0.00
2017-08-19    0.09
2017-08-20    0.00
2017-08-21    0.56
2017-08-22    0.50
2017-08-23    0.45
Name: prcp, Length: 2230, dtype: float64

In [109]:
# y_pos = np.arange(len(new_df))
# plt.bar(new_df.index.to_datetime(), new_df["prcp"], align='center', alpha=0.5)
# plt.xlabel("Date")
# plt.ylabel("Percipitation")
# plt.title("12 Month Data")
# plt.show()

new_df.plot(x=new_df.index, y=new_df["prcp"], kind='bar')

KeyError: "['0.0' '0.08' '0.08' ..., '0.56' '0.5' '0.45'] not in index"

In [113]:
new_df.describe()

        prcp
count   2230
unique   160
top      0.0
freq    1083

In [114]:
session.query(station).count()

9

In [171]:
q = session.query(measurement.station, func.count(measurement.date)).\
    group_by(measurement.station).\
    order_by(desc(func.count(measurement.date))).all()
q

[('USC00519281', 2772),
 ('USC00519397', 2724),
 ('USC00513117', 2709),
 ('USC00519523', 2669),
 ('USC00516128', 2612),
 ('USC00514830', 2202),
 ('USC00511918', 1979),
 ('USC00517948', 1372),
 ('USC00518838', 511)]

In [218]:
q = session.query(measurement.tobs).\
    filter(measurement.date >= "2016-08-23").\
    filter(measurement.station == "USC00519281").all()
q

[('77.0'),
 ('77.0'),
 ('80.0'),
 ('80.0'),
 ('75.0'),
 ('73.0'),
 ('78.0'),
 ('77.0'),
 ('78.0'),
 ('80.0'),
 ('80.0'),
 ('78.0'),
 ('78.0'),
 ('78.0'),
 ('73.0'),
 ('74.0'),
 ('80.0'),
 ('79.0'),
 ('77.0'),
 ('80.0'),
 ('76.0'),
 ('79.0'),
 ('75.0'),
 ('79.0'),
 ('78.0'),
 ('79.0'),
 ('78.0'),
 ('78.0'),
 ('76.0'),
 ('74.0'),
 ('77.0'),
 ('78.0'),
 ('79.0'),
 ('79.0'),
 ('77.0'),
 ('80.0'),
 ('78.0'),
 ('78.0'),
 ('78.0'),
 ('77.0'),
 ('79.0'),
 ('79.0'),
 ('79.0'),
 ('79.0'),
 ('75.0'),
 ('76.0'),
 ('73.0'),
 ('72.0'),
 ('71.0'),
 ('77.0'),
 ('79.0'),
 ('78.0'),
 ('79.0'),
 ('77.0'),
 ('79.0'),
 ('77.0'),
 ('78.0'),
 ('78.0'),
 ('78.0'),
 ('78.0'),
 ('77.0'),
 ('74.0'),
 ('75.0'),
 ('76.0'),
 ('73.0'),
 ('76.0'),
 ('74.0'),
 ('77.0'),
 ('76.0'),
 ('76.0'),
 ('74.0'),
 ('75.0'),
 ('75.0'),
 ('75.0'),
 ('75.0'),
 ('71.0'),
 ('63.0'),
 ('70.0'),
 ('68.0'),
 ('67.0'),
 ('77.0'),
 ('74.0'),
 ('77.0'),
 ('76.0'),
 ('76.0'),
 ('75.0'),
 ('76.0'),
 ('75.0'),
 ('73.0'),
 ('75.0'),
 ('73.0'),
 ('75.0'),
 ('74.0'),
 ('75.0'),
 ('74.0'),
 ('75.0'),
 ('73.0'),
 ('75.0'),
 ('73.0'),
 ('73.0'),
 ('74.0'),
 ('70.0'),
 ('72.0'),
 ('70.0'),
 ('67.0'),
 ('67.0'),
 ('69.0'),
 ('70.0'),
 ('68.0'),
 ('69.0'),
 ('69.0'),
 ('66.0'),
 ('65.0'),
 ('68.0'),
 ('62.0'),
 ('75.0'),
 ('70.0'),
 ('69.0'),
 ('76.0'),
 ('76.0'),
 ('74.0'),
 ('73.0'),
 ('71.0'),
 ('74.0'),
 ('74.0'),
 ('72.0'),
 ('71.0'),
 ('72.0'),
 ('74.0'),
 ('69.0'),
 ('67.0'),
 ('72.0'),
 ('70.0'),
 ('64.0'),
 ('63.0'),
 ('63.0'),
 ('62.0'),
 ('70.0'),
 ('70.0'),
 ('62.0'),
 ('62.0'),
 ('63.0'),
 ('65.0'),
 ('69.0'),
 ('77.0'),
 ('70.0'),
 ('74.0'),
 ('69.0'),
 ('72.0'),
 ('71.0'),
 ('69.0'),
 ('71.0'),
 ('71.0'),
 ('72.0'),
 ('72.0'),
 ('69.0'),
 ('70.0'),
 ('66.0'),
 ('65.0'),
 ('69.0'),
 ('68.0'),
 ('68.0'),
 ('68.0'),
 ('59.0'),
 ('60.0'),
 ('70.0'),
 ('73.0'),
 ('75.0'),
 ('64.0'),
 ('59.0'),
 ('59.0'),
 ('62.0'),
 ('68.0'),
 ('70.0'),
 ('73.0'),
 ('79.0'),
 ('75.0'),
 ('65.0'),
 ('70.0'),
 ('74.0'),
 ('70.0'),
 ('70.0'),
 ('71.0'),
 ('71.0'),
 ('71.0'),
 ('69.0'),
 ('61.0'),
 ('67.0'),
 ('65.0'),
 ('72.0'),
 ('71.0'),
 ('73.0'),
 ('72.0'),
 ('77.0'),
 ('73.0'),
 ('67.0'),
 ('62.0'),
 ('64.0'),
 ('67.0'),
 ('66.0'),
 ('81.0'),
 ('69.0'),
 ('66.0'),
 ('67.0'),
 ('69.0'),
 ('66.0'),
 ('68.0'),
 ('65.0'),
 ('74.0'),
 ('69.0'),
 ('72.0'),
 ('73.0'),
 ('72.0'),
 ('71.0'),
 ('76.0'),
 ('77.0'),
 ('76.0'),
 ('74.0'),
 ('68.0'),
 ('73.0'),
 ('71.0'),
 ('74.0'),
 ('75.0'),
 ('70.0'),
 ('67.0'),
 ('71.0'),
 ('67.0'),
 ('74.0'),
 ('77.0'),
 ('78.0'),
 ('67.0'),
 ('70.0'),
 ('69.0'),
 ('69.0'),
 ('74.0'),
 ('78.0'),
 ('71.0'),
 ('67.0'),
 ('68.0'),
 ('67.0'),
 ('76.0'),
 ('69.0'),
 ('72.0'),
 ('76.0'),
 ('68.0'),
 ('72.0'),
 ('74.0'),
 ('70.0'),
 ('67.0'),
 ('72.0'),
 ('60.0'),
 ('65.0'),
 ('75.0'),
 ('70.0'),
 ('75.0'),
 ('70.0'),
 ('79.0'),
 ('75.0'),
 ('70.0'),
 ('67.0'),
 ('74.0'),
 ('70.0'),
 ('75.0'),
 ('76.0'),
 ('77.0'),
 ('74.0'),
 ('74.0'),
 ('74.0'),
 ('69.0'),
 ('68.0'),
 ('76.0'),
 ('74.0'),
 ('71.0'),
 ('71.0'),
 ('74.0'),
 ('74.0'),
 ('74.0'),
 ('74.0'),
 ('80.0'),
 ('74.0'),
 ('72.0'),
 ('75.0'),
 ('80.0'),
 ('76.0'),
 ('76.0'),
 ('77.0'),
 ('75.0'),
 ('75.0'),
 ('75.0'),
 ('75.0'),
 ('72.0'),
 ('74.0'),
 ('74.0'),
 ('74.0'),
 ('76.0'),
 ('74.0'),
 ('75.0'),
 ('73.0'),
 ('79.0'),
 ('75.0'),
 ('72.0'),
 ('72.0'),
 ('74.0'),
 ('72.0'),
 ('72.0'),
 ('77.0'),
 ('71.0'),
 ('73.0'),
 ('76.0'),
 ('77.0'),
 ('76.0'),
 ('76.0'),
 ('79.0'),
 ('81.0'),
 ('76.0'),
 ('78.0'),
 ('77.0'),
 ('74.0'),
 ('75.0'),
 ('78.0'),
 ('78.0'),
 ('69.0'),
 ('72.0'),
 ('74.0'),
 ('74.0'),
 ('76.0'),
 ('80.0'),
 ('80.0'),
 ('76.0'),
 ('76.0'),
 ('76.0'),
 ('77.0'),
 ('77.0'),
 ('77.0'),
 ('82.0'),
 ('75.0'),
 ('77.0'),
 ('75.0'),
 ('76.0'),
 ('81.0'),
 ('82.0'),
 ('81.0'),
 ('76.0'),
 ('77.0'),
 ('82.0'),
 ('83.0'),
 ('77.0'),
 ('77.0'),
 ('77.0'),
 ('76.0'),
 ('76.0'),
 ('79.0')]

In [222]:
frequency = pd.DataFrame(q)
frequency

     tobs
0    77.0
1    77.0
2    80.0
3    80.0
4    75.0
5    73.0
6    78.0
7    77.0
8    78.0
9    80.0
10   80.0
11   78.0
12   78.0
13   78.0
14   73.0
15   74.0
16   80.0
17   79.0
18   77.0
19   80.0
20   76.0
21   79.0
22   75.0
23   79.0
24   78.0
25   79.0
26   78.0
27   78.0
28   76.0
29   74.0
..    ...
322  72.0
323  74.0
324  74.0
325  76.0
326  80.0
327  80.0
328  76.0
329  76.0
330  76.0
331  77.0
332  77.0
333  77.0
334  82.0
335  75.0
336  77.0
337  75.0
338  76.0
339  81.0
340  82.0
341  81.0
342  76.0
343  77.0
344  82.0
345  83.0
346  77.0
347  77.0
348  77.0
349  76.0
350  76.0
351  79.0

[352 rows x 1 columns]

In [225]:
frequency.plot.hist(by=frequency["tobs"].astype(float), bins=12)

TypeError: Empty 'DataFrame': no numeric data to plot