In [1]:
import pandas as pd

In [2]:
data = "resources/measurement.csv"
data2 = "resources/station.csv"

In [40]:
measurements = pd.read_csv(data)
stations = pd.read_csv(data2)
pd.isnull(measurements)

          id  station   date   prcp   tobs
0      False    False  False  False  False
1      False    False  False  False  False
2      False    False  False  False  False
3      False    False  False  False  False
4      False    False  False   True  False
5      False    False  False  False  False
6      False    False  False  False  False
7      False    False  False  False  False
8      False    False  False  False  False
9      False    False  False  False  False
10     False    False  False  False  False
11     False    False  False  False  False
12     False    False  False  False  False
13     False    False  False  False  False
14     False    False  False  False  False
15     False    False  False  False  False
16     False    False  False  False  False
17     False    False  False  False  False
18     False    False  False  False  False
19     False    False  False  False  False
20     False    False  False  False  False
21     False    False  False  False  False
22     False    False  False  False  False
23     False    False  False  False  False
24     False    False  False  False  False
25     False    False  False  False  False
26     False    False  False   True  False
27     False    False  False  False  False
28     False    False  False  False  False
29     False    False  False   True  False
...      ...      ...    ...    ...    ...
19520  False    False  False  False  False
19521  False    False  False  False  False
19522  False    False  False  False  False
19523  False    False  False  False  False
19524  False    False  False  False  False
19525  False    False  False  False  False
19526  False    False  False  False  False
19527  False    False  False  False  False
19528  False    False  False   True  False
19529  False    False  False  False  False
19530  False    False  False  False  False
19531  False    False  False   True  False
19532  False    False  False   True  False
19533  False    False  False  False  False
19534  False    False  False  False  False
19535  False    False  False  False  False
19536  False    False  False  False  False
19537  False    False  False   True  False
19538  False    False  False  False  False
19539  False    False  False   True  False
19540  False    False  False  False  False
19541  False    False  False  False  False
19542  False    False  False  False  False
19543  False    False  False  False  False
19544  False    False  False   True  False
19545  False    False  False  False  False
19546  False    False  False   True  False
19547  False    False  False  False  False
19548  False    False  False  False  False
19549  False    False  False  False  False

[19550 rows x 5 columns]

In [41]:
pd.isnull(stations)

      id  station   name  latitude  longitude  elevation  location
0  False    False  False     False      False      False     False
1  False    False  False     False      False      False     False
2  False    False  False     False      False      False     False
3  False    False  False     False      False      False     False
4  False    False  False     False      False      False     False
5  False    False  False     False      False      False     False
6  False    False  False     False      False      False     False
7  False    False  False     False      False      False     False
8  False    False  False     False      False      False     False

In [39]:
measurements.fillna(value =0)

          id      station        date  prcp  tobs
0          1  USC00519397  2010-01-01  0.08  65.0
1          2  USC00519397  2010-01-02  0.00  63.0
2          3  USC00519397  2010-01-03  0.00  74.0
3          4  USC00519397  2010-01-04  0.00  76.0
4          5  USC00519397  2010-01-06  0.00  73.0
5          6  USC00519397  2010-01-07  0.06  70.0
6          7  USC00519397  2010-01-08  0.00  64.0
7          8  USC00519397  2010-01-09  0.00  68.0
8          9  USC00519397  2010-01-10  0.00  73.0
9         10  USC00519397  2010-01-11  0.01  64.0
10        11  USC00519397  2010-01-12  0.00  61.0
11        12  USC00519397  2010-01-14  0.00  66.0
12        13  USC00519397  2010-01-15  0.00  65.0
13        14  USC00519397  2010-01-16  0.00  68.0
14        15  USC00519397  2010-01-17  0.00  64.0
15        16  USC00519397  2010-01-18  0.00  72.0
16        17  USC00519397  2010-01-19  0.00  66.0
17        18  USC00519397  2010-01-20  0.00  66.0
18        19  USC00519397  2010-01-21  0.00  69.0
19        20  USC00519397  2010-01-22  0.00  67.0
20        21  USC00519397  2010-01-23  0.00  67.0
21        22  USC00519397  2010-01-24  0.01  71.0
22        23  USC00519397  2010-01-25  0.00  67.0
23        24  USC00519397  2010-01-26  0.04  76.0
24        25  USC00519397  2010-01-27  0.12  68.0
25        26  USC00519397  2010-01-28  0.00  72.0
26        27  USC00519397  2010-01-30  0.00  70.0
27        28  USC00519397  2010-01-31  0.03  67.0
28        29  USC00519397  2010-02-01  0.01  66.0
29        30  USC00519397  2010-02-03  0.00  67.0
...      ...          ...         ...   ...   ...
19520  19521  USC00516128  2017-07-24  0.84  77.0
19521  19522  USC00516128  2017-07-25  0.30  79.0
19522  19523  USC00516128  2017-07-26  0.30  73.0
19523  19524  USC00516128  2017-07-27  0.00  75.0
19524  19525  USC00516128  2017-07-28  0.40  73.0
19525  19526  USC00516128  2017-07-29  0.30  77.0
19526  19527  USC00516128  2017-07-30  0.30  79.0
19527  19528  USC00516128  2017-07-31  0.00  74.0
19528  19529  USC00516128  2017-08-01  0.00  72.0
19529  19530  USC00516128  2017-08-02  0.25  80.0
19530  19531  USC00516128  2017-08-03  0.06  76.0
19531  19532  USC00516128  2017-08-05  0.00  77.0
19532  19533  USC00516128  2017-08-06  0.00  79.0
19533  19534  USC00516128  2017-08-07  0.05  78.0
19534  19535  USC00516128  2017-08-08  0.34  74.0
19535  19536  USC00516128  2017-08-09  0.15  71.0
19536  19537  USC00516128  2017-08-10  0.07  75.0
19537  19538  USC00516128  2017-08-11  0.00  72.0
19538  19539  USC00516128  2017-08-12  0.14  74.0
19539  19540  USC00516128  2017-08-13  0.00  80.0
19540  19541  USC00516128  2017-08-14  0.22  79.0
19541  19542  USC00516128  2017-08-15  0.42  70.0
19542  19543  USC00516128  2017-08-16  0.42  71.0
19543  19544  USC00516128  2017-08-17  0.13  72.0
19544  19545  USC00516128  2017-08-18  0.00  76.0
19545  19546  USC00516128  2017-08-19  0.09  71.0
19546  19547  USC00516128  2017-08-20  0.00  78.0
19547  19548  USC00516128  2017-08-21  0.56  76.0
19548  19549  USC00516128  2017-08-22  0.50  76.0
19549  19550  USC00516128  2017-08-23  0.45  76.0

[19550 rows x 5 columns]

In [42]:
measurements.to_csv("clean_measurements.csv")

In [43]:
stations.to_csv("clean_stations.csv")